GET  http://8.135.44.223/test
content-type: application/json


###


GET http://localhost:8000/mongo/food
content-type: application/json


###

GET http://localhost:9004/tableByDate/1
content-type: application/json

###

GET http://localhost:9004/tableByShop/168048393
content-type: application/json

###

GET http://localhost:9004/rules
content-type: application/json

###

POST http://localhost:9004/plan
content-type: application/json

{
  "oid": 76325,
  "name": "123",
  "q": "1231",
  "a": "123131"
}

###

GET http://localhost:9004/plans
content-type: application/json

###

GET http://localhost:9004/plan/2038543739
content-type: application/json

###

GET http://localhost:9005/user_acts/小伍/0
content-type: application/json